//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvAssistant.Mac.TestMy.WCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.IMvAssistantWCFService")]
    public interface IMvAssistantWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMvAssistantWCFService/GetData", ReplyAction="http://tempuri.org/IMvAssistantWCFService/GetDataResponse")]
        string GetData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMvAssistantWCFService/GetData", ReplyAction="http://tempuri.org/IMvAssistantWCFService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMvAssistantWCFService/UtHalMaskTransfer_TestPathMove", ReplyAction="http://tempuri.org/IMvAssistantWCFService/UtHalMaskTransfer_TestPathMoveResponse")]
        int UtHalMaskTransfer_TestPathMove(MvAssistant.Mac.v1_0.Hal.Assembly.MacHalMaskTransfer mt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMvAssistantWCFService/UtHalMaskTransfer_TestPathMove", ReplyAction="http://tempuri.org/IMvAssistantWCFService/UtHalMaskTransfer_TestPathMoveResponse")]
        System.Threading.Tasks.Task<int> UtHalMaskTransfer_TestPathMoveAsync(MvAssistant.Mac.v1_0.Hal.Assembly.MacHalMaskTransfer mt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMvAssistantWCFServiceChannel : MvAssistant.Mac.TestMy.WCFService.IMvAssistantWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MvAssistantWCFServiceClient : System.ServiceModel.ClientBase<MvAssistant.Mac.TestMy.WCFService.IMvAssistantWCFService>, MvAssistant.Mac.TestMy.WCFService.IMvAssistantWCFService {
        
        public MvAssistantWCFServiceClient() {
        }
        
        public MvAssistantWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MvAssistantWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MvAssistantWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MvAssistantWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public int UtHalMaskTransfer_TestPathMove(MvAssistant.Mac.v1_0.Hal.Assembly.MacHalMaskTransfer mt) {
            return base.Channel.UtHalMaskTransfer_TestPathMove(mt);
        }
        
        public System.Threading.Tasks.Task<int> UtHalMaskTransfer_TestPathMoveAsync(MvAssistant.Mac.v1_0.Hal.Assembly.MacHalMaskTransfer mt) {
            return base.Channel.UtHalMaskTransfer_TestPathMoveAsync(mt);
        }
    }
}
